CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'docker123';
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'docker123';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;